### ISSUE TITLE
Grammatical fixes in documentation

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/45DaysOfReactJS#1]
Fixes for grammatical errors are welcomed through PRs. Also, if you certain easy and quick ReactJS project ideas, you can add them to the README of this repo.

**Comment by neupanedipen** [comment]
I would like to add some beginner level project ideas in react. Can i go ahead to open a pull request?

**Comment by DemonDaddy22** [comment]
Yes, of course, @neupanedipen, if possible add some reference links as well so that it's easier for others to get started.
