### ISSUE TITLE
Webpage slows down on changing colour through a color-picker

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/45DaysOfReactJS#2]
There's an issue with the color-picker in the color-picker module, where changing the color slows down the page.

**Comment by Shivank-Dev** [comment]
I am interested in this

**Comment by DemonDaddy22** [comment]
@Shivank-Dev sure I can assign this issue to you, just go through the contribution guidelines once, and then start working on this.

**Comment by Shivank-Dev** [comment]
Okay thanks @DemonDaddy22

**Comment by Shivank-Dev** [comment]
It's working fine on my machine. Could you please share some recorded video of the issue so that it will easy for me to debug.

**Comment by DemonDaddy22** [comment]
Did you try continuously changing the colours through colour-picker, or simply click at different points?
Because there's an onChange function which gets fired every time you change the colour, I suppose that's the reason why it slows down.

**Comment by Shivank-Dev** [comment]
I have tried but unable  to create that scenario

**Comment by DemonDaddy22** [comment]
Maybe it's happening on my machine only, and that too on local version. The deployed version is running just fine.
