### ISSUE TITLE
Copy icon and colour code on hovering over colour card in colour picker

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/45DaysOfReactJS#3]
Need to show colour code and a copy button in the corner when hovering over a colour card.

**Comment by Jaikishann** [comment]
Hi @DemonDaddy22,
I would like to take this up.

**Comment by DemonDaddy22** [comment]
Sure @Jaikishann, read the contribution guidelines once, I'll assign this to you.

**Comment by Jaikishann** [comment]
Hi @DemonDaddy22, I have given a PR addressing the above issue. Please check it out.
