### ISSUE TITLE
Add guide to contribute

### ISSUE THREAD

**Issue by Aqsa48** [DemonDaddy22/45DaysOfReactJS#33]
Enhancing Readme.md documentation by adding step by step guide how one can contribute on ideas.

**Comment by DemonDaddy22** [comment]
Can you please elaborate on your concern, as there are the contributing guide and sample idea format to help a person contribute towards the project

**Comment by Aqsa48** [comment]
step by step guide to contribute in ideas.md if one is very new to open source contribution.

**Comment by DemonDaddy22** [comment]
Okay, so you made contributions yourself, and I feel you might know what can be improved, so you can add the changes in IDEAS.md and CONTRIBUTING.md so that it'll be much easier for absolute beginners.
Also, make sure you take the pull of the latest code.
For any doubts or help, feel free to ask.
