### ISSUE TITLE
Add checks on pull requests to master

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/45DaysOfReactJS#5]
Add tests and checks which get triggered on pull requests to master, so that the current functionality doesn’t break.

**Comment by nihonjinrxs** [comment]
Are there any tests written currently? If not, is there a particular testing library you prefer? Are you looking for Github Actions or some other CI service?

**Comment by DemonDaddy22** [comment]
No @nihonjinrxs, I haven't added any tests yet. 
Yes, I was looking for GitHub actions, I've added a YAML file which initiates the build process every time some code is pushed onto the master branch, now I want some basic tests/checks to be fired as well whenever there's a pull request which informs the person whether the PR is valid or not.

**Comment by phanlyhuynh** [comment]
Hi. Can you assign to me? I can add test for Github actions. It run test for each some code is pushed onto the master branch. I think i add eslint and check it on Github actions. Thanks!!!

**Comment by DemonDaddy22** [comment]
Hi @phanlyhuynh, I have already added GitHub action when code is pushed to master which builds the application and deploys it to GitHub pages, I want tests to run on 'pull-requests' which check if the PR is valid and not breaking anything. If you can add this, then I'll assign this to you.
